### ISSUE TITLE
Error upon mousing over / clicking a icon

### ISSUE THREAD

**Issue by Jayshua83** [steventroughtonsmith/instanceportals#1]
I am getting an error when clicking an icon on the map ONLY after installing your addon.

Interface\AddOns\!BugGrabber\BugGrabber.lua:357: attempt to call global 'date' (a string value)

It shows up as BugGrabber but per BugGrabber author... (That doesn't really make a difference. BugGrabber stops grabbing errors when one of your addons is producing too many, so one of your addons it at fault here.)

Any idea what is causing this?

**Comment by steventroughtonsmith** [comment]
Thanks! I will check it out and get back to you. I expect it's a silent name collision that BugGrabber is picking up and surfacing to the UI - if that is the purpose of BugGrabber. There's only one reference to a 'date' in this project and it's not used for anything

**Comment by steventroughtonsmith** [comment]
Hoping v1.4 fixes this one.
