### ISSUE TITLE
Beta waypoints 

### ISSUE THREAD

**Issue by gaveer** [steventroughtonsmith/instanceportals#15]
№ | Dungeon | Zone | Coordinates

1 | The Necrotic Wake | Bastion | 40.0 55.3 | 
2 | Spires of Ascension | Bastion | 58.4 28.7 | 
3 | Plaguefall | Maldraxxus | 59.2 64.8 |
4 | Theater of Pain | Maldraxxus | 53 53 | 
5 | De Other Side | Ardenweald | 68.7 66.1 |
6 | Mists of Tirna Scithe | Ardenweald | 35.4 53.9 | 
7 | Halls of Atonement | Revendreth | 78.3 49.1 | 
8 | Sanguine Depths | Revendreth | 50.9 29.9 | 
9 | Castle Nathria Raid | Revendreth | 46.2 / 41.2 |

**Comment by steventroughtonsmith** [comment]
Thanks for this! I have integrated support for Shadowlands' instances in 6c234975cb774aca58b976be024a8625ad8c88d2. This post was very helpful.
