### ISSUE TITLE
11.0.2 causes Instance Portals to no longer function

### ISSUE THREAD

**Issue by karpana** [steventroughtonsmith/instanceportals#19]
on login, I'm getting the following error
```lua
29x InstancePortals/IPCore.lua:4: attempt to call global 'LoadAddOn' (a nil value)
[string "@InstancePortals/IPCore.lua"]:4: in function `InstancePortalUI_OnLoad'
[string "*InstancePortals.xml:9_OnLoad"]:2: in function <[string "*InstancePortals.xml:9_OnLoad"]:1>

Locals:
self = InstancePortalUI {
}
(*temporary) = nil
(*temporary) = "Blizzard_WorldMap"
(*temporary) = "attempt to call global 'LoadAddOn' (a nil value)"
```

I suspect this is related to the surprise API changes that blizz implemented yesterday

**Comment by karpana** [comment]
looking at what other addons have done to work around this issue, i've added this line of code right before the breaking line (at line 4 of IPCore.lua), and it fixes the issue (and I think maintains reverse compatibilty with other version of wow like classic)

```lua
local LoadAddOn = C_AddOns.LoadAddOn or LoadAddOn
```

**Comment by steventroughtonsmith** [comment]
Thanks for letting me know! Pushing a fix shortly

**Comment by karpana** [comment]
Looks like CurseForge is on their A-Game, as it looks like the updated release just came through.   

downloaded and reloaded.
No more errors.

Thank you @steventroughtonsmith .  Much appreciated.

**Comment by steventroughtonsmith** [comment]
👌
