### ISSUE TITLE
Error Opening Map in "Ruins of Ogudei" MOP Rep Mine?

### ISSUE THREAD

**Issue by Jayshua83** [steventroughtonsmith/instanceportals#2]
4x InstancePortals\ipCore.lua:75: attempt to index field '?' (a nil value)
InstancePortals\ipCore.lua:75: in function `IPUIRefreshPins'
InstancePortals\ipCore.lua:268: in function <InstancePortals\ipCore.lua:267>
[C]: in function `SetMapToCurrentZone'
FrameXML\WorldMapFrame.lua:320: in function <FrameXML\WorldMapFrame.lua:300>
[C]: ?
[C]: ?
[C]: ?
[C]: in function `Show'
FrameXML\UIParent.lua:2165: in function `SetUIPanel'
FrameXML\UIParent.lua:1970: in function `ShowUIPanel'
FrameXML\UIParent.lua:1880: in function <FrameXML\UIParent.lua:1876>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:2630: in function `ShowUIPanel'
FrameXML\UIParent.lua:2614: in function `ToggleFrame'
FrameXML\WorldMapFrame.lua:218: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
mapName = "Krasarang"
textureHeight = 668
_ = 768
isMicroDungeon = true
microDungeonMapName = "RuinsofOgudei"
cityOverride = false
dungeonLevel = 1
(*temporary) = nil
(*temporary) = false
(*temporary) = -750
(*temporary) = -731.875
(*temporary) = -575
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
IPUIDebug = false

**Comment by Jayshua83** [comment]
Any fixes for this? Very annoying to have this coming up on indoor maps... Have to disable the addon till fixed. :(

**Comment by steventroughtonsmith** [comment]
Planning on an update when the 7.0 pre-patch hits, if you can manage until then? Will make sure it's fixed

**Comment by steventroughtonsmith** [comment]
Should be fixed in v1.4 (which should show up on Curse in the next day or so). Let me know if not
